[package]
name = "badascii-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
egui_dock = "0.16.0"
egui_extras = "0.31.1"
env_logger = "0.11.7"
rand = "0.8.5"
roughr = "0.9.0"
badascii = { path = "../badascii" }

[dev-dependencies]
expect-test = "1.5.1"
