setup:
    rustup target add wasm32-unknown-unknown
    cargo install --locked trunk
    
serve:
    trunk serve

release:
    trunk build --release
    
deploy:
    just release
    cd dist && zip deploy.zip *
