[package]
name = "badascii-doc"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
badascii = { version = "0.1.0", path = "../badascii" }
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = "2.0.100"

[dev-dependencies]
expect-test = "1.5.1"
