[package]
name = "badascii-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
badascii = { version = "0.1.0", path = "../badascii" }
badascii-doc = { version = "0.1.0", path = "../badascii-doc" }
clap = { version = "4.5.36", features = ["derive"] }
