mod analyze;
pub mod rect;
pub mod render;
pub mod svg;
pub mod tc;
pub mod text_buffer;
pub use render::RenderJob;
pub use roughr::core::Options;
pub use text_buffer::TextBuffer;
//pub mod png;
pub mod bitmap;
